get http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "ahmed",
    "email": "swosdrdcom@sdfhgdf.com",
    "password":"azahfgsdfge",
    "ksdlkgsd" : "ljkgtlidzs"
    

}