get http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "abdjhglkh",
    "email": "abdollah@sdfhgfddf.com",
    "password":"abdolbjhglgfguy365"
    

}

###
DELETE  http://localhost:3000/api/users/1

###
PATCH  http://localhost:3000/api/users/15

{
    "name": "nedday",
    "email": "nedday@sqgyrthd.com",
    "password":"sdd213213egrdg"
    

}


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "",
    "email": "retu@sqgyrthd.com",
    "password":"sddsdfsdegrdg"
    

}

###

PATCH  http://localhost:3000/api/users/14
Content-Type: application/json

{
    "name": "eraoui",
    "email": "eraoui@sqezrtgyrthd.com",
    "password":"fdgsdfgfsdqg"
    

}
###
DELETE    http://localhost:3000/api/articles/2

###
POST  http://localhost:3000/api/articles
Content-Type: application/json


{
    "title": "edgfsgr",
    "description" : "gdsfg",
    "url" : "dgsf",
    "content": "ahmed gsdfgeraoui est un personne qui va faire toutes ce qu'ik faut faire",
    "userId" : 3,
    "categories" : ["1", "2"]

}
###
get  http://localhost:3000/api/articles

###
PATCH   http://localhost:3000/api/articles/3
Content-Type: application/json

{

    "published" : false

}


###
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "content" : "you look great brother",
    "userId" :  3,
    "articleId" : 4
} 

###
DELETE    http://localhost:3000/api/comments/3

###
PATCH   http://localhost:3000/api/comments/4
Content-Type: application/json


{
    "content" : "yassine el hanafi w anass nedday maxi rjal hhh"
}

###
GET http://localhost:3000/api/categories

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name" : "Neflix"
}